projects/proj1/pokeportal/config/routes.rb
Rails.application.routes.draw do
  devise_for :trainers
  root to: "home#index"
  resources :trainers
end

projects/proj1/pokeportal/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

projects/proj1/pokeportal/app/models/trainer.rb
class Trainer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

projects/proj1/pokeportal/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

projects/proj1/pokeportal/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    trainerless_pokemon = Pokemon.where(trainer: nil)
    @pokemon = trainerless_pokemon.sample
  end

end

projects/proj1/pokeportal/app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_action :authenticate_trainer!

  def index
    @trainers = Trainer.all
  end

  def show
    @trainer = Trainer.find(params[:id])
  end

end

projects/proj1/pokeportal/app/helpers/application_helper.rb
module ApplicationHelper
end

projects/proj1/pokeportal/app/views/home/index.html.erb
<h3>Welcome to PokePortal</h3>
<p><%= link_to 'Trainers:', trainers_path %> <%= Trainer.count %> registered</p>

<% if @pokemon and current_trainer %>
  <% if @pokemon.ndex %>
    <%= image_tag("pokemon/#{@pokemon.ndex}.png", alt: "pokemon") %>
  <% end %>
  <p> A wild <%= @pokemon.name %> has appeared!</p>
  <!-- REPLACE THIS LINE BELOW -->
  <div>THIS SHALL BE REPLACED</div>
<% end %>

<%= image_tag("pokemon/pokemon-family.jpg", :alt => "pokemon") %>

projects/proj1/pokeportal/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

projects/proj1/pokeportal/app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'PokePortal Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul class="right">
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

projects/proj1/pokeportal/app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<% if trainer_signed_in? %>
  <li><%= link_to 'Edit Your Trainer', edit_trainer_registration_path %></li>
  <li><%= link_to 'Log Out', destroy_trainer_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Log In', new_trainer_session_path %></li>
  <li><%= link_to 'Join PokePortal', new_trainer_registration_path %></li>
<% end %>

projects/proj1/pokeportal/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PokePortal" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "PokePortal" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

projects/proj1/pokeportal/app/views/trainers/_trainer.html.erb
<td><%= link_to trainer.name, trainer %></td>
<td><%= link_to trainer.email, trainer %></td>

projects/proj1/pokeportal/app/views/trainers/index.html.erb
<div class="container">
  <div class="row">
    <h3>Trainers</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @trainers.each do |trainer| %>
            <tr>
              <%= render trainer %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

projects/proj1/pokeportal/app/views/trainers/show.html.erb
<h3>Trainer</h3>
<p>Name: <%= @trainer.name if @trainer.name %></p>
<p>Email: <%= @trainer.email if @trainer.email %></p>